CREATE TABLE IF NOT EXISTS Users
(
Id CHAR(36) PRIMARY KEY,
FirstName VARCHAR (30) NOT NULL,
LastName VARCHAR (30) NOT NULL,
PhoneNumber VARCHAR (15) NOT NULL,
Email VARCHAR (50) NOT NULL,
HashedPassword VARCHAR(255) NOT NULL,
Salt VARCHAR (50) NOT NULL,
Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
Updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Rooms
(
Id CHAR(36) PRIMARY KEY,
RoomName VARCHAR (30) NOT NULL,
Capacity TINYINT NOT NULL,
MonitorAvailable BOOL NOT NULL,
Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
Updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS RoomReservations
(
Id CHAR(36) PRIMARY KEY,
UserId CHAR(36) NOT NULL,
RoomId CHAR(36) NOT NULL,
StartTime TIMESTAMP NOT NULL,
EndTime TIMESTAMP NOT NULL,
Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
Updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (UserId) REFERENCES Users(Id),
FOREIGN KEY (RoomId) REFERENCES Rooms(Id)
);
